name:  Bug Report
description: Reportar un bug o comportamiento inesperado
title: "[BUG]: "
labels: ["type: bug", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar este bug. Completa la informaci贸n para reproducirlo.
  
  - type: dropdown
    id: area
    attributes:
      label: rea afectada
      options:
        - Backend (FastAPI/Django)
        - Frontend (React/Next.js)
        - AI Agents (Pydantic AI/LangGraph)
        - Database (PostgreSQL/Supabase)
        - Infrastructure (Dokploy/Railway)
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del bug
      placeholder: "Descripci贸n clara del comportamiento inesperado..."
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1. Ir a '...'
        2. Click en '...'
        3. Observar error
      render: markdown
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Logs relevantes
      render: shell
  
  - type: input
    id: version
    attributes:
      label: Versi贸n
      placeholder: "v1.2.3"
    validations:
      required: true
  
  - type: dropdown
    id: environment
    attributes:
      label: Entorno
      options:
        - Development (local)
        - Staging (Railway)
        - Production (Vercel/Hetzner)
    validations:
      required: true
